import type {App,Env,Identity} from './types';
import {all,first,id,error} from './db';
import {ensureDocumentAccess,ensureOrganizationMember} from './collaboration';
import {isApprovedEmail} from './auth';
import {validateSource} from './authoring-pdf';
const base='/api/organizations/:org/documents/:doc/reviews';
async function mac(env:Env,id:string){const encoder=new TextEncoder(),key=await crypto.subtle.importKey('raw',encoder.encode(env.AUTH_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(`drive-review:${id}`))),x=>x.toString(16).padStart(2,'0')).join('');}
export async function reviewToken(env:Env,id:string){return `${id}.${await mac(env,id)}`;}
async function document(env:Env,user:Identity,org:string,doc:string,admin=false){if(user.serviceScope)throw error(403,'Review requires your Google account');const role=await ensureOrganizationMember(env,user,org);if(admin&&!['owner','admin'].includes(role))throw error(403,'Only owners and admins can share review links');const d=await ensureDocumentAccess(env,user,doc,'read');if(d.organization_id!==org||d.is_deleted)throw error(404,'Document not found');return d;}
async function publicReview(env:Env,token:string){
 const [id,actual]=token.split('.');if(!/^rev_[a-f0-9]{24}$/.test(id||'')||actual?.length!==64)throw error(404,'Review link unavailable');const expected=await mac(env,id);let diff=0;for(let i=0;i<64;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);if(diff)throw error(404,'Review link unavailable');
 const r=await first(env,'SELECT r.*,d.name document_name,d.organization_id FROM document_reviews r JOIN documents d ON d.id=r.document_id WHERE r.id=?',id);if(!r)throw error(404,'Review link unavailable');if(r.status!=='open'||r.expires_at<Date.now())throw error(410,'Review is closed');
 const u=await first(env,'SELECT * FROM users WHERE id=?',r.created_by);if(!u||u.disabled_at||!isApprovedEmail(u.email,u.email_verified===1))throw error(410,'Review is closed');
 const organizations=await all(env,'SELECT o.id,o.name,m.role FROM organizations o JOIN organization_members m ON m.organization_id=o.id WHERE m.user_id=?',u.id);const identity={userId:u.id,email:u.email,name:u.name,organizations} as Identity;try{await document(env,identity,r.organization_id,r.document_id,true);}catch{throw error(410,'Review is closed');}return r;
}
export function registerReviewRoutes(app:App){
 app.use('/api/reviews/*',async(c,next)=>{c.header('Referrer-Policy','no-referrer');c.header('X-Robots-Tag','noindex, noarchive');await next();});
 app.get(base,async c=>{const d=await document(c.env,c.get('identity'),c.req.param('org'),c.req.param('doc'));const role=await ensureOrganizationMember(c.env,c.get('identity'),d.organization_id),canShare=['owner','admin'].includes(role);let canResolve=true;try{await ensureDocumentAccess(c.env,c.get('identity'),d.id,'write');}catch{canResolve=false;}
 const rows=await all(c.env,'SELECT * FROM document_reviews WHERE document_id=? ORDER BY created_at DESC LIMIT 20',d.id);const proposals=await all(c.env,'SELECT p.*,r.version_id,a.source_json original_source FROM review_proposals p JOIN document_reviews r ON r.id=p.review_id LEFT JOIN authored_versions a ON a.version_id=r.version_id WHERE r.document_id=? ORDER BY (p.status=\'pending\') DESC,p.created_at DESC LIMIT 100',d.id);
 return c.json({canShare,canResolve,versionId:d.current_version_id,reviews:await Promise.all(rows.map(async r=>({...r,url:canShare?`${c.env.APP_URL}/review/${await reviewToken(c.env,r.id)}`:undefined}))),proposals:proposals.map(p=>({...p,source:p.source_json?JSON.parse(p.source_json):null,originalSource:p.original_source?JSON.parse(p.original_source):null,source_json:undefined,original_source:undefined}))});
 });
 app.post(base,async c=>{const d=await document(c.env,c.get('identity'),c.req.param('org'),c.req.param('doc'),true),now=Date.now();const row={id:id('rev'),version_id:d.current_version_id};await c.env.DB.prepare("INSERT INTO document_reviews(id,document_id,version_id,created_by,created_at,expires_at) SELECT ?,?,?,?,?,? FROM documents WHERE id=? AND current_version_id=? AND is_deleted=0").bind(row.id,d.id,row.version_id,c.get('identity').userId,now,now+30*86400000,d.id,row.version_id).run();if(!await first(c.env,'SELECT id FROM document_reviews WHERE id=?',row.id))throw error(409,'Document changed; try again');return c.json({url:`${c.env.APP_URL}/review/${await reviewToken(c.env,row.id)}`},201);});
 app.post(`${base}/:reviewId/revoke`,async c=>{const d=await document(c.env,c.get('identity'),c.req.param('org'),c.req.param('doc'),true);await c.env.DB.prepare("UPDATE document_reviews SET status='closed' WHERE id=? AND document_id=?").bind(c.req.param('reviewId'),d.id).run();return c.json({ok:true});});
 app.post(`${base}/proposals/:proposalId/resolve`,async c=>{const d=await document(c.env,c.get('identity'),c.req.param('org'),c.req.param('doc'));await ensureDocumentAccess(c.env,c.get('identity'),d.id,'write');const b=await c.req.json();if(!['accepted','rejected'].includes(b.status))throw error(400,'Invalid review action');const p=await first(c.env,'SELECT p.* FROM review_proposals p JOIN document_reviews r ON r.id=p.review_id WHERE p.id=? AND r.document_id=?',c.req.param('proposalId'),d.id);if(!p)throw error(404,'Proposal not found');if(p.source_json&&b.status==='accepted')throw error(400,'Publish the proposed revision to accept its changes');await c.env.DB.prepare("UPDATE review_proposals SET status=?,resolved_at=?,resolved_by=? WHERE id=? AND status='pending'").bind(b.status,Date.now(),c.get('identity').userId,p.id).run();return c.json({ok:true});});
 app.get('/api/reviews/:token',async c=>{const r=await publicReview(c.env,c.req.param('token')),a=await first(c.env,'SELECT source_json FROM authored_versions WHERE version_id=?',r.version_id);return c.json({id:r.id,name:r.document_name,versionId:r.version_id,source:a?JSON.parse(a.source_json):null});});
 app.get('/api/reviews/:token/file',async c=>{const r=await publicReview(c.env,c.req.param('token')),v=await first(c.env,'SELECT storage_key FROM versions WHERE id=? AND document_id=?',r.version_id,r.document_id),object=v&&await c.env.FILES.get(v.storage_key);if(!object)throw error(404,'PDF unavailable');c.header('Content-Type','application/pdf');c.header('Content-Disposition','inline');return c.body(object.body);});
 app.post('/api/reviews/:token/proposals',async c=>{const r=await publicReview(c.env,c.req.param('token'));if(!(await c.env.AUTH_LIMITER.limit({key:`review:${c.req.header('CF-Connecting-IP')||'local'}`})).success)throw error(429,'Please wait before submitting again');const b=await c.req.json();if(typeof b.key!=='string'||!/^[a-f0-9]{32}$/.test(b.key))throw error(400,'Invalid submission key');const proposalId=`proposal_${b.key}`,name=String(b.name||'').trim(),comment=String(b.comment||'').trim();if(!name||name.length>100||comment.length>5000||(!comment&&!b.source))throw error(400,'Enter your name and a comment or proposed changes');
 const existing=await first(c.env,'SELECT review_id FROM review_proposals WHERE id=?',proposalId);if(existing){if(existing.review_id!==r.id)throw error(409,'Submission key already used');return c.json({ok:true});}
 let source:null|string=null;if(b.source){if(!await first(c.env,'SELECT version_id FROM authored_versions WHERE version_id=?',r.version_id))throw error(400,'This PDF has no editable native source');try{source=JSON.stringify(validateSource(b.source));}catch(e){throw error(400,(e as Error).message);}}
 const result=await c.env.DB.prepare("INSERT INTO review_proposals(id,review_id,name,comment,source_json,created_at) SELECT ?,?,?,?,?,? FROM document_reviews r JOIN documents d ON d.id=r.document_id WHERE r.id=? AND r.status='open' AND r.expires_at>? AND d.is_deleted=0 AND d.current_version_id=r.version_id").bind(proposalId,r.id,name,comment,source,Date.now(),r.id,Date.now()).run();if(!result.meta.changes)throw error(409,'This document has changed or review is closed. Ask for a fresh review link.');return c.json({ok:true},201);
 });
}
